add test for has title
adrianmaciuc/break-it-playwright-javascript-project pull request #85
Opened 2023-11-27 20:18 UTC by AndreeaHasel

test has title

2023-11-27 20:43 UTC, simonleventeattila submitted a review, later dismissed

2023-11-27 21:55 UTC, AlexStefan17 commented on tests/AndreeaHasel.spec.js
>  const { test, expect } = require("@playwright/test");
import { test, expect } from "@playwright/test";
Try use this syntax, it's more readable

2023-11-27 21:55 UTC, AlexStefan17 requested changes
import { test, expect } from "@playwright/test";
Try use this syntax, it's more readable. Otherwise it s fine.

2023-11-28 16:19 UTC, adrianmaciuc submitted a review, later dismissed

2023-11-28 20:58 UTC, AlexStefan17 approved these changes

2023-11-28 21:00 UTC, Iulian99 approved these changes

2023-12-02 10:18 UTC, closed without merging