added search tests
adrianmaciuc/break-it-playwright-javascript-project pull request #92
Opened 2023-12-08 21:27 UTC by AlexStefan17

2023-12-10 00:05 UTC, adrianmaciuc commented on tests/search/search.spec.js
> +  await page.waitForTimeout(1000);
nevermind, you do need this, its really tricky here. again this website is complicated

2023-12-10 00:05 UTC, adrianmaciuc commented on tests/search/search.spec.js
> +  await expect(await page.locator(pagination)).toHaveCount(0);
```suggestion
  await expect((await page.locator(products).all())).toHaveLength(3);

  await expect(await page.locator(pagination)).not.toBeVisible()
```

I see you didn't read my tip nr 8[ from my blog ](https://blog.martioli.com/playwright-tips-and-tricks-1/)

2023-12-10 00:05 UTC, adrianmaciuc commented on tests/search/search.spec.js
> +  await expect(sugestionAmount).toBe("25");
You write it nice, but the only part that was a bit confusing for me was how hard it is to read the indexOf line and figure out what you are doing. Sometimes the builtin methods of playwright provide a more easy readable way.

2023-12-10 23:14 UTC, pmirel commented on tests/search/search.spec.js
> +  // Enter "pants" and get sugestions
you can remove the comments

2023-12-10 23:32 UTC, pmirel requested changes
other than what adi already said, remove the comments and add a link to the ticket in decription.

2023-12-10 23:32 UTC, pmirel commented on tests/search/search.spec.js
> +  }
Is this necessary? all already returns a list of array. Can you make the assertion on that list?

2023-12-10 23:32 UTC, pmirel commented on tests/search/search.spec.js
> +  }
nevermind adi already wrote the code

2023-12-11 10:40 UTC, pmirel approved these changes

2023-12-11 10:46 UTC, pmirel requested changes

2023-12-11 10:46 UTC, pmirel commented on tests/search/search.spec.js
> +  // Enter "tee" and click on desired sugestion
remove comm

2023-12-11 10:46 UTC, pmirel commented on tests/search/search.spec.js
> +  // Get number of pages
remove comm

2023-12-11 10:46 UTC, pmirel commented on tests/search/search.spec.js
> +  // Enter "tee" and click on desired sugestion
remove comm

2023-12-11 10:46 UTC, pmirel commented on tests/search/search.spec.js
> +});
you acctualy try to use .toBeHidden() 
And remove 0 from argument

2023-12-11 12:04 UTC, pmirel approved these changes

2023-12-11 19:58 UTC, adrianmaciuc approved these changes

2023-12-12 08:38 UTC, merged